### ISSUE TITLE
[Tool][Omega-T] Omega-T終了時に、Targetフォルダの翻訳結果ファイルが元に戻る 

### ISSUE THREAD

**Issue by hfukuchi** [lf-j/OpenSourceComplianceHandbook-Translation#1]
・OmegaT起動中
・翻訳文生成を行うと、Targetフォルダに翻訳結果が生成される。
・OmegaT終了
・Targetフォルダの翻訳結果が元の英文に戻っている。

・チーム機能を一時期使っていて、チーム機能が生きていて、何か悪さをしている可能性がある。
谷口さん報告の以下の件と同類の可能性がある。
https://github.com/OpenChain-Project/Specification-Translation-JP/issues/1

**Comment by maabou512** [comment]
結論はどうでしたか？

**Comment by hfukuchi** [comment]
原因は同じだと思います。OmegaTのチーム機能が生きていて、書き換えてしまいます。
OmegaTのチーム機能を外せなくて（原因不明）、暫定対策としては以下を取っています。
　「OmegaTのアプリ終了前に、いったん翻訳結果を生成し、それを別の場所に保存しておく。
　　GitHubへコミットするときには、この保存した翻訳結果を使用する。」

**Comment by maabou512** [comment]
承知しました。とりあえず、一旦クローズしてしまってよいのではないでしょうか。あと、Issue#2の方は、まず最初のレビューをして全体のトーンを見てからにします。3ページ分ぐらいで、単なるモチベーションの問題だと思うので（笑）、当方を想定していただいて構いませんです。

**Comment by hfukuchi** [comment]
暫定対策で対応できているので、いったんクローズします。
