### ISSUE TITLE
[Translation] Prefaceに対する翻訳文提案

### ISSUE THREAD

**Issue by hfukuchi** [lf-j/OpenSourceComplianceHandbook-Translation#10]
谷口さんからの提案：　（継続検討中。忘れないようにIssueに上げておきます）
「 +オープンソース コンプライアンスに携わるようになったのは、ソフトウェア開発者として私のキャリアが始まったころでした。そこから今に至る20年、オープンソース コンプライアンスは直接的に
も間接的にも私の仕事の一部であり続けています。オープンソース ソフトウェアと共に歩んできた私の旅ですが、振り返るとオープンソース コンプライアンスにおける実践的（プラクティカル）な情報を探すのが大変だった旅でした。
 +そういったこともあり私自身の経験を公開することに興味が湧いてきました。私の経験を公開することでいろいろな人たちが何かを学び、そして学んだ人が経験したことを公開するようになり、さらに私たち皆が産業において製品デリバリの期間やエンジニアリング リソースに与えるインパクトを最小限にとどめるよう、オープンソース コンプライアンスを実現する、よりよいやり方に向けた取り組みに尽力できるのではないか、と。
 +このハンドブックは、まさにそういった企業でオープンソース コンプライアンスを推進してきた私の経験をまとめたものであり、オープンソース コンプライアンスプログラムの整備、その運営についての実践的側面にフォーカスしたものとなっています。ただ私の経験の大半が（CやC++が主要プログラミング言語である）組み込み領域中心だったため、本ハンドブックでは全般的にその傾向が色濃く出ている点についてはご留意いただければと思います。
 +皆さんがオープン ソース コンプライアンスを実現するべく、日々の推進活動で本書が役立ってくれることを願ってやみません。 」

**Comment by maabou512** [comment]
ありがとうございます。第1パラグラフの後半がいまいちですね。以下を代案として記載しておきます。

- 現状→「実践的（プラクティカル）な情報を探すのが大変だった旅でした。」
- 修正案→「実践的（プラクティカル）な情報を見つけるのに苦労した旅でした。」

**Comment by hfukuchi** [comment]
翻訳案を採用することにします。
Pull Requestを作成しました。

**Comment by hfukuchi** [comment]
Pull Request #16で取り込みました。
クローズします。
