### ISSUE TITLE
レビュー(Tani)  P13-P15 " Foreword" 

### ISSUE THREAD

**Issue by maabou512** [lf-j/OpenSourceComplianceHandbook-Translation#25]
福地さん
Foreword 部分（P13-15)の当方レビューを記載します。よろしくお願いいたします。

1. 和訳レビュー前（江川さん or 福地さん）、
2. 当方レビュー後案、
3. 原文

の順で記載していきます。一応当方ブランチのOmega-Tファイルにはコメントも書いておきました。
（tani ブランチ）　本内容は以下にもおいておきます。

### [https://github.com/lf-j/OpenSourceComplianceHandbook-Translation/tree/tani/review/tani-review](https://github.com/lf-j/OpenSourceComplianceHandbook-Translation/tree/tani/review/tani-review)
---------------------------------------------------------------------
■１．和訳レビュー前（江川さん or 福地さん）：

序文（Foreword）

オープン ソースは、ソフトウェアや知的財産に関わる個人によってリードされた理想主義的な運動からばかりでなく、オープン ソースがIT戦略における主要な部分であると認識して、オープン ソース開発に参加したいと考えているような（政府、企業、大学などの）組織における活動によっても、広がってきています。Linuxや他のオープン ソース技術における初期段階の成功は、技術の全ての分野にも広がってきています。

伝統的な組織も注目しています。オープンソース ソフトウェアを優先度の高い項目に挙げ、ソフトウェアを組織活動で戦略的優位を得るために使っています。
エンタープライズITでのオープン ソースの利用は、2010年から倍増しています。

調査した企業の78%は、オープン ソース上でビジネスを運用しています。

64%が、現在、オープン ソース プロジェクトに参加しています。

39%が、自社のオープン ソース プロジェクトを立ち上げています。

ノースブリッジ＆ブラックダック
「オープン ソース未来予測2015」

「オープン ソース ファースト：納税者のお金で開発された全てのソリューションは、納税者のものに（オープン ソース）」GSAにおいて開発された全てのコードは、オープン ライセンスのもとに共有されるべきであり、他の人々はそれから便益を受けることができます。加えて、自分たちが設計したソリューションとしてのオープン ソース ソフトウェアを優先的に利用していきます。
CIOオフィス 米国連邦調達庁（年間660億ドルの調達を行う米国政府機関）

「ブロックチェーン技術の開発は、金融サービス業界の業務や経済構造を再定義する可能性を秘めています。業界が、もっと積極的に、もっと効率的に、もっとディジタル化を促進しようと努力している、そういう重要な時期に現れています。オープン ソース開発は、イノベーションを加速させ、この技術の大規模な利用の促進を助けてくれるでしょう。我々はHyperledgerプロジェクトをサポートしていることに誇りを感じています。」
リチャード ラム, Chief Executive, 財務サービス, Accenture

「成長し活気ある開発コミュニティへのメンバー投資から、Dronecodeプロジェクトの初年度はかなりエキサイティングなものです。共通プラットフォームを確立するために共に努力し、オープン ソース ベスト プラクティスを利用することで、カメラからクラウドにまで広がるドローン アプリケーションの基盤を確立することができます。Dronecodeの「フルスタック」プラットフォーム アプローチは、メンバーのハードウェアとソフトウェアのイノベーションを結合しており、自律的で、環境を認識し、継続的にネット接続されている新世代ドローンを作り出すことでしょう。それは、飛行するIoTです。」
クリス アンダーセン　CEO　3DR
（ワイアード マガジン 前編集長、「ロング テール」著者）

「オープン ソースは、我々の開発に本質的なものです。偉大なソリューションを構築するために、人々を共に作業させるパワフルなアプローチです。そこからは実際にメリットが共有されます。」
ロブ アレキサンダー, CIO, Capital One

組織は、オープン ソース コミュニティへの適切な参加や、法的で責任あるやり方での参加の最善な方法についてのガイダンスを探しています。参加者は、コードとIPを共有することを望み、IP資産（商標、著作権、特許）のための、信頼のおける中立的な管理場所を必要としています。リソース プール（財政、技術）のフレームワークを必要としています。

参加者は、効果的な方法で、自分の競争者といかに協力するかについてのトレーニングを必要としています。そのためにも、本書は、オープン ソース ライセンスの精神と法的項目を固守しながらも、共有される価値とイノベーションを創造する最善の方法について共有理解を作り出すことに焦点を合わせています。 
 
■２．和訳（当方レビュー後案）

前書き（Foreword）

オープン ソースの動きは、ソフトウェアや知的財産に携わる人々による個人レベルの理想主義的活動からだけではなく、（政府、企業、大学といった）組織レベルの、オープン ソースがIT戦略の重要なパーツであるという気づきやその開発へ参加する必要性からくる活動としても広がりました。草創期の成功事例であったLinux、その他オープンソース テクノロジは技術分野の関連のすべてへと普及しました。

よりトラディショナルな企業も気づき始めています；オープンソース ソフトウェアの優先するようにして、これを経営の戦略的優位を得るために使うようになってきているのです。

- エンタープライズITのオープン ソースの使用は2010年から2倍になった。

- 調査対象企業の78%が、オープン ソースを活用した事業運営をしている。
 
- 現時点でその64%が、オープン ソース プロジェクトに参加している。
 
- その39%は自らオープンソース プロジェクトを立ち上げることを計画している。

**North Bridge社 および Black Duck社によるサーベイ
「The 2015 Future of Open Source Survey」**

「オープンソース ファースト：税金で開発したソリューションはどんなものであれ納税者のドメインに（オープン ソースで）あるべきでしょう。

GSA( General Services Administration、米国連邦調達庁）として開発したコードのすべてはオープンソース ライセンスの下で共有されるべきで、そうすることで多くの人々が恩恵を得ることができると思います。さらに今我々が設計するソリューションでもオープンソース ソフトウェアの使用を優先させていくつもりです。」

**米国連邦調達庁 CIOオフィス （年間660億ドルの調達を行う米国政府機関）**

「ブロックチェーン技術の開発には、金融サービス業界の業務や経済を再定義できるポテンシャルがあります。この業界が、もっと積極的に、もっと効率的に、もっとディジタルになろうと努力している、そういう重要な時期にこの技術はでてきました。オープン ソース開発がこういったイノベーションを加速し、この技術がスケールすることを促進してくれるでしょう。Hyperledgerプロジェクトをサポートしていることを我々は誇りに思います。」
**アクセンチュア 社　財務サービス チーフエグゼクティブ　リチャード ラム**

「参加メンバによる投資が増えたことに始まり、活発な開発コミュニティに成長したことに至るまで、Droncode プロジェクトの最初の年は最高にエキサイティングなものとなりました。共通的なプラットフォームを作りあげるために努力を結集させ、オープンソースのベストプラクティスを活かすことによって、カメラからクラウドに至る、ドローンアプリケーションの新しい時代に向けた素地を形作ることができるのです。参加メンバーが持つハードウェアとソフトウェアのイノベーションを結合させたDroncodeの『フルスタック』プラットフォームのアプローチは、自律的で、環境を認識し、継続的につながる、いわば空飛ぶIoTとして新世代のドローンをもたらすことになるでしょう。」

**3DR社 CEO クリス アンダーセン
（ワイアード マガジン 前編集長、「ロング テール」著者）**

「オープンソースは、我々の開発プロセスに不可欠なものです。それは人々に協業を促し、皆のよさを共有しながら壮大なソリューションを作り上げる強力なアプローチなのです。」
**Capital One社 CIO ロブ アレキサンダー**

企業は今、適切にかつ法に則り、そして責任あるやり方でオープンソースコミュニティに参加する最善の方法となるガイドを探し求めています。参加する企業は、コードと知財（IP）の共有を求め、知財資産（商標、著作権、特許）のための信頼できる中立な「家（Home）」を必要としています。また、（金銭面、技術面などで）リソースをプールする枠組みも必要としています。競合となる企業とのコラボレーションを効果的にどのようにやるのか、その術を得るための専門的な助言も必要としています。本書では、こういったことを目的として、オープンソース ライセンスの精神と法令上の詳細に従いつつ、共有価値（Shared value）やイノベーションを生み出すための最良の方法についての理解を共有することに焦点を当てていきます。

■３．原文

Foreword

Open source has expanded not only from an idealistic movement led by individuals around software and intellectual property but from one where organizations (e.g., governments, companies, and universities) realize that open source is a key part of their IT strategy and want to participate in its development. Early success in Linux and other open source technologies has spread to all areas of technology.

More traditional organizations are also taking notice; they are making open source software a priority and using the software for strategic advantage in their operations. 
Use of open source in enterprise IT has doubled since 2010.

78% of surveyed companies run their businesses on open source.

64% currently participate in open source projects.

39% plan to launch their own open source projects.

North Bridge & Black Duck
“The 2015 Future of Open Source Survey”

“Open Source First: Simply put, any solution developed using taxpayer dollars should be in the taxpayer’s domain (open source). At GSA, we believe that all code we developed should be shared under an open license so others may benefit from it. In addition, we will give priority to using open source software as we design now solutions.”
Office of the CIO, U.S. General Services Administration (U.S. agency that oversees $66 billion of procurement annually)

“The development of Blockchain technology has the potential to redefine the operations and economics of the financial services industry. It emerges at an important time, as the industry strives to be leaner, more efficient, and more digital. Open source development will accelerate the innovation and help drive the scalability of this technology, and we are proud to support the Hyperledger Project.”
Richard Lumb, Chief Executive, Financial Services, Accenture

“From increasing member investments to a growing, vibrant developer community, the Dronecode Project’s first year has been extremely exciting. By bringing efforts together to establish a common platform and utilizing open source best practices, we’re able to build the foundation for a new era of drone applications that extend from the camera to the cloud. The Dronecode ‘full-stack’ platform approach, combined with the hardware and software innovations of its members, will bring about a new generation of drones that are autonomous, aware of their environments, and continuously connected - an airborne Internet of Things.”
Chris Anderson, CEO, 3DR
(Former Editor in Chief of Wired magazine and author of “The Long Tail”)

“Open source is essential to our development process. It’s a powerful approach that lets people work together to build great solutions while realizing shared benefits.”
Rob Alexander, CIO, Capital One

Organizations are looking for guidance on how best to participate appropriately in open source communities and to do so in a legal and responsible way. Participants want to share their code and IP, and they need a trusted neutral home for IP assets (trademark, copyright, patents). They also need a framework to pool resources (financial, technical, etc.).

Participants need expertise to train them how to collaborate with their competitors in an effective manner. To that end, this book is geared to creating a shared understanding on the best ways to create shared value and innovation while adhering to the spirit and legal particulars of open source licensing. 

---------------------------------------------------------------------

**Comment by hfukuchi** [comment]
ご提案に関して、訳を変更したほうが良いと考える理由があれば、教えて下さい。
提案を拒否しているわけではなく、受け入れ可否の判断をどうするかの材料として質問しております。

**Comment by hfukuchi** [comment]
Pull Request♯30にて、ご提案の一部を受領しました。

**Comment by hfukuchi** [comment]
クローズします。
