### ISSUE TITLE
[Tool][Omega-T]　Omega-Tの別のバージョンで表示すると、原文の分節がずれている

### ISSUE THREAD

**Issue by hfukuchi** [lf-j/OpenSourceComplianceHandbook-Translation#6]
異なるOSを搭載した2台のPC上にインストールされたOmega-Tで作業すると、PC間で、原文の分節の表示が異なる部分がある。

**Comment by hfukuchi** [comment]
再入力を実施。Pull Request ♯11, Pull Request ♯12

**Comment by MieSato** [comment]
すみません。closeされた後で、いまさらなのですが。
これは[設定]→[分節化規則の設定]の[英語]の分節化規則が異なっているのではないでしょうか。

**Comment by hfukuchi** [comment]
ご指摘を受けましたので、再オープンします。

**Comment by hfukuchi** [comment]
確認しましたところ、ご指摘のように、[分節化規則の設定]の[英語]の分節化規則が異なっていました。

この設定は、Project情報等に保存されないのですね。
何かのドキュメントやReadmeに記載していましたでしょうか？

**Comment by MieSato** [comment]
こちら、当初bitbucketを使用していた時に、OmegaTの初期設定で変更したと思います。
今確認したところ、
1月12日付けのメール「Open Compliance Handbook (by Ibrahim) の翻訳について」と
1月13日付けのMLメール「OmegaT分節化規則」などにこのやりとりがあります。

**Comment by MieSato** [comment]
基本的な分節化設定は、メンバーで共有したほうがよいですね。
ただし各自がこのプロジェクト以外の翻訳作業でOmegaTを使用している場合、作業を進める中でカスタマイズすると思いますので、それらすべてを共有する必要はないかな、と思います。

**Comment by hfukuchi** [comment]
このファイルですね。

英語の分節化設定ファイル：
[english segmentation.xlsx](https://github.com/lf-j/OpenSourceComplianceHandbook-Translation/files/1230539/english.segmentation.xlsx)

**Comment by MieSato** [comment]
はい。そうです。

**Comment by hfukuchi** [comment]
分節化規則（英語用）をHandbookのレポジトリに登録しました。

この規則ファイルは、チーム内で共通なので、lf-j/OpenChain-Trans_FOR_TEAMにも登録したほうが良いですね。
　https://github.com/lf-j/OpenChain-Trans_FOR_TEAM

**Comment by hfukuchi** [comment]
解決しましたのでクローズします。
